# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: Check for Module Updates

on:
  # schedule:
  #   - cron: '0 0,12 * * *'  # Twice a day
  workflow_dispatch:
  # pull_request_target:
  #   types: [opened, reopened, synchronize]
  # merge_group:
  #   types: [checks_requested]

jobs:
  check-updates:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4.2.2


      - name: Run version checker script
        id: check_versions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r tools/requirements.txt
          python scripts/check_and_update_modules.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: Update modules
          author: score-automations[bot] <score-bot@users.noreply.github.com>
          body: |
            This PR updates the modules to their latest versions.
            Please review and merge if everything looks good.
          commit-message: Update modules
          # We need to use a different token than GITHUB_TOKEN, so that PR triggers all the PR-workflows.
          token: ${{ secrets.SCORE_BOT_PAT }}
