# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: Check for Module Updates

on:
  schedule:
    - cron: '0 0,12 * * *'  # Twice a day
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  check-updates:
    runs-on: ubuntu-latest

    # permissions must be set even when using a PAT
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4.2.2
        # with:
        #   token: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug PAT
        run: |
          echo "SCORE_BOT_PAT is set: [${{ secrets.SCORE_BOT_PAT != '' }}]"
          echo "GITHUB_TOKEN is set: [${{ secrets.GITHUB_TOKEN != '' }}]"
        env:
          SCORE_BOT_PAT: ${{ secrets.SCORE_BOT_PAT }}

      - name: "Debug PAT: /user"
        run: |
          curl -s -H "Authorization: token $SCORE_BOT_PAT" https://api.github.com/user
        env:
          SCORE_BOT_PAT: ${{ secrets.SCORE_BOT_PAT }}

      - name: "Debug PAT: /repos/eclipse-score/bazel_registry"
        run: |
          curl -s -H "Authorization: token $SCORE_BOT_PAT" https://api.github.com/repos/eclipse-score/bazel_registry
        env:
          SCORE_BOT_PAT: ${{ secrets.SCORE_BOT_PAT }}

      - name: "Debug PAT: /user/repos"
        run: |
          curl -s -H "Authorization: token $SCORE_BOT_PAT" https://api.github.com/user/repos?per_page=100
        env:
          SCORE_BOT_PAT: ${{ secrets.SCORE_BOT_PAT }}

      - name: Run version checker script
        id: check_versions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r tools/requirements.txt
          python scripts/check_and_update_modules.py


      - name: Configure git author
        run: |
          git config user.name "eclipse-score-bot"
          git config user.email "eclipse-score-bot@users.noreply.github.com"

      - name: Commit changes
        run: |
          git add -A
          git commit -m "chore: modules update"
        id: commit

      - name: Create branch, push, and open PR
        run: |
          set -euo pipefail
          git switch -C "$BRANCH"

          # Force origin to use the PAT
          # git remote set-url origin "https://x-oauth-basic:${GH_TOKEN}@github.com/${{ github.repository }}.git"

          # Push the branch (create or update)
          git push -u origin "$BRANCH"

        env:
          # GH_TOKEN: ${{ secrets.SCORE_BOT_PAT }}   # PAT belongs to eclipse-score-bot
          BRANCH: bot/modules-update
          PR_BASE: main
          PR_TITLE: "chore: modules update"
          PR_BODY: "Automated update via gh CLI (from fork)."
 