# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: License Check
# License Check is its own workflow, as it runs on pull_request_target
# events in order to be able to access the Dash API token.
# We avoid pull_request_target in other workflows, as it's extremely uncomfortable
# to work with, as it runs in the context of the base branch, not the PR branch.

on:
  pull_request_target:
    types: [opened, reopened, synchronize]
  merge_group:
    types: [checks_requested]

permissions:
  pull-requests: write
  issues: write

jobs:
  license-check:
    uses: eclipse-score/cicd-workflows/.github/workflows/license-check.yml@main
    secrets:
      dash-api-token: ${{ secrets.ECLIPSE_GITLAB_API_TOKEN }}
    with:
      bazel-target: run //tools:license-check
