name: Pull Request Workflow
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  verify_registry:
    name: 🧪 Verify Registry
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Check out
        uses: actions/checkout@v4

      - name: 🛠️ Setup Python Dependencies
        run: pip install -r tools/requirements.txt

      - name: 🔍 Check bazel registry
        run: python src/registry_manager/main.py --check

  self_test:
    name: 🔬 Self Test
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Check out
        uses: actions/checkout@v4

      - name: 🛠️ Setup Python Dependencies
        run: pip install -r tools/requirements.txt

      - name: 🧩 Run pytest
        run: pytest tests
